spring:
  application:
    name: balance-service
  datasource:
    url: jdbc:mysql://mysql:3306/balance_service?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: redis    # 改为 redis 服务名
    port: 6379
  rocketmq:
    name-server: rmqnamesrv:9876    # 改为 namesrv 服务名
    producer:
      group: ${spring.application.name}_producer
      send-message-timeout: 3000
      retry-times-when-send-failed: 2
      retry-times-when-send-async-failed: 0
      compress-message-body-threshold: 4096
      max-message-size: 4194304
      retry-next-server: true
    consumer:
      group: ${spring.application.name}_consumer
      pull-batch-size: 10
      topic: transaction_recovery
      consume-from-where: CONSUME_FROM_LAST_OFFSET
      thread-min: 20
      thread-max: 20
      consume-message-batch-max-size: 1
      consume-timeout: 15
  mvc:
    servlet:
      path: /api